#!/bin/ksh
file="/home/cloudera/Downloads/input/hotel_bookings.csv"
count=1
delay=5

while IFS= read line
do
        # display $line or do something with $line
	if [ $count -ne 1 ]; then
		echo "$line"
		modulo=$(( $count  % 11 ))
		if [ $modulo -eq 0 ]; then
   			sleep $delay
	
		fi
			#count=$[$count +1]		
	fi
	count=$[$count+1]
	
done <"$file"

